- name: Provision to local network
  hosts: local-kvm
  vars:
    devstack_libvirt_type: kvm
    devstack_user: ubuntu
    devstack_group: ubuntu
    devstack_password: openstack
    devstack_token: devtoken
    devstack_version: stable/juno
    devstack_host_ip: 192.168.1.116
    devstack_nat_if: eth0
  roles:
    - common
    - devstack-common
    - devstack-vm
