- name: Provision common parts
  hosts: all
  vars:
    devstack_libvirt_type: qemu
    devstack_user: vagrant
    devstack_group: vagrant
    devstack_password: openstack
    devstack_token: devtoken
    devstack_version: master
    devstack_host_ip: 192.168.70.10
    devstack_nat_if: eth0
  roles:
    - common
    - devstack-common
    - devstack-docker
